name: Noetic

on: [push, pull_request]

jobs:
  industrial_ci:
    env:
      # See the full documentation here:
      # https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst
      CXX: /usr/bin/clang++
      CC: /usr/bin/clang
    strategy:
      fail-fast: false
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
